### ISSUE TITLE
Refactor to BoxHeads

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/BoxHeads3D#36]
## Planned outcome:
- Changed background images and styles to fit the theme of the boxheads game, instead of soccerheads
- Changed lobby scene:
  - Max players in a lobby: 4
  - Player table, listing:
    - Player names
    - Ready status
    - Player colors
    - Kick buttons for the host

## Tasks:
- [ ] Change background images in the menu scenes
- [ ] Change the titles to "Box Heads"
- [ ] Adjust the CreateLobby Method, so that lobbies have a maximum of 4 players
- [ ] Delete the player prefabs, their names, and everything related to them in the lobby scene
- [ ] Create a table in the lobby scene
- [ ] Create a prefab for a line in the lobby table containing the player's icon, name, ready status and kick button (for the host)
- [ ] Adjust the code to work with this scene
