### ISSUE TITLE
Player Movement

### ISSUE THREAD

**Issue by DarioLoll** [DarioLoll/BoxHeads3D#39]
## Planned outcome:
For now, each player should be represented by a capsule
- The player should be able to move the capsule with W, A, S, D keys
- The camera should always be positioned on the upper half of the capsule (first person perspective)
- The player should be able to run, but only in the facing direction, when holding down shift + W

## Tasks:
- [ ] Create a player prefab (3D capsule with a box collider and rigidbody)
- [ ] Make the camera a child of the player so it follows the player
- [ ] Create an input action map and map the WASD keys to a Vector 2 action of type value
- [ ] Generate a c# class for the input action map
- [ ] Create a script that will handle player movement
- [ ] Move the player in the update method using the generated class for the input action map
- [ ] Make the movement speed configurable
- [ ] Add a configurable running speed
- [ ] Add the shift key to the input action map
- [ ] Subscribe to the event that is fired when shift is held
- [ ] Figure out how to only increase the speed in the forward direction
- [ ] Document the code

## Notes:
This issue may not be fully planned out.
